name: Reindex Algolia Crawler on Deployment Success

on:
  push:
    branches: 
      - main
    paths:
      - 'content/docs/**/*.md'
      - 'content/changelog/**/*.md'
      - '!content/docs/README.md' # Exclude the README.md file
      - '!content/docs/shared-content/**/*.md' # Exclude the shared-content folder
  deployment_status:
  
jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event deployment_status
        run: echo "${{ toJson(github.event.deployment_status) }}"
      - name: Print GitHub event deployment
        run: echo "${{ toJson(github.event.deployment) }}"

  reindex-algolia:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags, necessary for the correct working of git diff.
    
    - name: Check for new  file
      id: file-check
      run: |
        git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changes.txt
        echo "Added files:"
        added_files=$(cat changes.txt | grep '^A' | awk '{print $2}')  # Filters out only the added files.
        content_files=$(echo $added_files | grep '^content')  # Filters added files to find those starting with 'content'.
        echo $content_files
        if [ -z "$content_files" ]; then
          echo "::set-output name=new_content_file::false"  # Sets the output variable 'new_content_file' to false if no new 'content' files are added.
        else
          echo "::set-output name=new_content_file::true"  # Sets it to true if new 'content' files are added.
        fi
      
    
    - name: Reindex Algolia Crawler if new file added
      if: steps.file-check.outputs.new_content_file == 'true'  # Conditionally runs this step only if new files are added.
      env:
        CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
        CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
        CRAWLER_ID: ${{ secrets.CRAWLER_ID }}
      run: |
        curl -H "Content-Type: application/json" -X POST \
        --user $CRAWLER_USER_ID:$CRAWLER_API_KEY \
        "https://crawler.algolia.com/api/1/crawlers/$CRAWLER_ID/reindex"  # Executes the curl command to reindex Algolia Crawler.