name: Deployment and File Check Workflow

on: 
  deployment_status:

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetches the last two commits for comparison
          
      - name: Output Deployment Info
        run: |
          echo "Deployment Status: ${{ github.event.deployment_status.state }}"
          echo "GitHub Ref Name: ${{ github.ref_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event Name: ${{ github.event.release.tag_name }}"

  check-and-reindex:
    needs: debug-info
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetches the last two commits for comparison

      - name: Check for new file in specific paths
        run: |
          git diff --name-status ${{ github.event.deployment_status.sha }}^ ${{ github.event.deployment_status.sha }} | grep '^A' | egrep 'content/docs/|content/changelog/|content/postgresql/' > changes.txt
          echo "Added files:"
          cat changes.txt
          if [ -s changes.txt ]; then
            echo "New files detected in specified paths."
            echo "::set-env name=NEW_FILES_DETECTED::true"
          else
            echo "No new files added in specified paths."
            echo "::set-env name=NEW_FILES_DETECTED::false"
          fi

      - name: Reindex Algolia
        if: env.NEW_FILES_DETECTED == 'true'
        env:
          CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
          CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
          CRAWLER_ID: ${{ secrets.CRAWLER_ID }}
        run: |
          curl -H "Content-Type: application/json" -X POST \
          --user $CRAWLER_USER_ID:$CRAWLER_API_KEY \
          "https://crawler.algolia.com/api/1/crawlers/$CRAWLER_ID/reindex"
