name: Deployment and File Check Workflow

on: 
  deployment_status:

jobs:
  check-and-reindex:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for new file
        run: |
          git fetch origin ${GITHUB_REF#refs/heads/}:refs/remotes/origin/${GITHUB_REF#refs/heads/}
          git diff --name-status origin/${GITHUB_REF#refs/heads/} ${{ github.event.deployment_status.sha }} > changes.txt
          echo "Added files:"
          added_files=$(cat changes.txt | grep '^A' | awk '{print $2}')
          echo $added_files
          if [ -z "$added_files" ]; then
            echo "No new files added."
            exit 0  # Exit if no new files are found
          fi

      - name: Reindex Algolia
        if: env.added_files
        env:
          CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
          CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
          CRAWLER_ID: ${{ secrets.CRAWLER_ID }}
        run: |
          curl -H "Content-Type: application/json" -X POST \
          --user $CRAWLER_USER_ID:$CRAWLER_API_KEY \
          "https://crawler.algolia.com/api/1/crawlers/$CRAWLER_ID/reindex"
