name: Reindex Algolia Crawler on Deployment Success

on: deployment_status

jobs:
  debug-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event deployment_status
        run: echo "${{ toJson(github.event.deployment_status) }}"
      - name: Print GitHub event deployment
        run: echo "${{ toJson(github.event.deployment.ref) }}"
        
  reindex-algolia:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for new Markdown file
        id: file-check
        run: |
          git diff --name-status ${{ github.event.deployment_status.sha }} ${{ github.sha }} > changes.txt
          echo "Added files:"
          added_files=$(cat changes.txt | grep '^A' | awk '{print $2}')
          echo $added_files
          if [ -z "$added_files" ]; then
            echo "::set-output name=new_file::false"
          else
            echo "::set-output name=new_file::true"
          fi

      - name: Reindex Algolia Crawler if new file added
        if: steps.file-check.outputs.new_file == 'true'
        env:
          CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
          CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
          CRAWLER_ID: ${{ secrets.CRAWLER_ID }}
        run: |
          curl -H "Content-Type: application/json" -X POST \
          --user $CRAWLER_USER_ID:$CRAWLER_API_KEY \
          "https://crawler.algolia.com/api/1/crawlers/$CRAWLER_ID/reindex"
