name: Reindex Algolia Crawler on Deployment Success

on:
  push:
    branches:
      - main
    paths:
      - 'content/**/*.md'
  deployment_status:

jobs:
  check-markdown:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      markdown_added: ${{ steps.markdown-check.outputs.markdown_added }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for new Markdown files
        id: markdown-check
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || echo "No new markdown files"
          if [ $? -eq 0 ]; then
            echo "::set-output name=markdown_added::true"
          else
            echo "::set-output name=markdown_added::false"
          fi
    
  trigger-algolia:          
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && needs.check-markdown.outputs.markdown_added == 'true'
    runs-on: ubuntu-latest
    needs: [check-markdown]
    steps:
      - name: Reindex Algolia Crawler if new file added
        env:
          CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
          CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}
          CRAWLER_ID: ${{ secrets.CRAWLER_ID }}
        run: |
          curl -H "Content-Type: application/json" -X POST \
          --user $CRAWLER_USER_ID:$CRAWLER_API_KEY \
          "https://crawler.algolia.com/api/1/crawlers/$CRAWLER_ID/reindex"  # Executes the curl command to reindex Algolia Crawler.
